StockApp-Task6
AlexandrRumyantsev/Stocks pull request #1
Opened 2023-10-24 17:06 UTC by AlexandrRumyantsev

https://github.com/AlexandrRumyantsev/Stocks/assets/46137399/31ea1b55-482a-48a2-8276-70ee4ce1ef70

2023-10-24 17:21 UTC, LuckyDmitry commented
Текст сливается, нужно добавить отступы

2023-10-24 17:44 UTC, LuckyDmitry requested changes

2023-10-24 17:44 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksInfoUseCase.kt
> +        }.await().subList(0,10)
Если у нас меньше 10 элементов? 
Давай в Констану вынесем

2023-10-24 17:44 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksInfoUseCase.kt
> +        val firstTenStocksAsString =
stockSymbols? Скорее

2023-10-24 17:44 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksInfoUseCase.kt
> +            businessLogicHelper.doWork(domainDataItem)
doWork ничего не говорит

2023-10-24 17:44 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/StocksAdapter.kt
> +            if(isGrow){
Лучше более длинные переменные, чем те, из которых не понятно, что это значит

2023-10-24 17:44 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/StocksAdapter.kt
> +                if (position%2 == 0) R.color.card_bg else R.color.white
Отступы

2023-10-24 17:44 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/StocksAdapter.kt
> +    class Comparator: DiffUtil.ItemCallback<SnippetData>(){
Отступы

2023-10-24 17:52 UTC, LuckyDmitry requested changes

2023-10-24 17:52 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/data/DataRepositoryImpl.kt
>      private val api: ServerDataApi
Давай более явные имена, serverDataApi что то общее, нужно более конкретное имя

2023-10-24 17:52 UTC, indie-contributor commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/data/DataRepositoryImpl.kt
> +    override suspend fun getStockInfo(symbol: String): List<StockInfoModel> {
getStockInfo, но возвращаем list?

2023-10-24 17:52 UTC, indie-contributor commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/data/ServerDataApi.kt
> +    companion object{
Отступы

2023-10-24 17:52 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/di/AppModule.kt
>          return BusinessLogicHelperImpl()
Название не удачное

2023-10-24 17:52 UTC, indie-contributor commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/BusinessLogicHelperImpl.kt
> -        return params.copy(title = "qwerty")
Ничего не делает. Зачем оставил?

2023-10-24 17:52 UTC, LuckyDmitry commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksInfoUseCase.kt
> +                .shuffled()
Давай операторы filter, shuffled писать с новой строки, чтобы читать было проще

2023-10-24 17:52 UTC, indie-contributor commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksInfoUseCase.kt
> +        val result = mutableListOf<SnippetData>()
Тут лучше использовать map

2023-10-24 18:16 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/data/DataRepositoryImpl.kt
> +    override suspend fun getStockInfo(symbol: String): List<StockInfoModel> {
Этот запрос возвращает list из одного элемента, так устроен api, поэтому пришлось сделать возвращаемое значение листом, хотя по факту - это должна быть одна моделька.

2023-10-26 09:37 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/domain/GetStocksInfoUseCase.kt
> +        val result = mutableListOf<SnippetData>()
В таком случае мы будем отправлять 10 запросов вместо одного, почему будет лучше map?

> Тут лучше использовать map

2023-10-26 16:24 UTC, ilsave commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/StocksAdapter.kt
> +            if(hasPriceIncreased){
отступы

2023-10-26 16:24 UTC, ilsave commented on app/src/main/java/com/example/cleanarchitectureshowcase/features/home/presentation/StocksFragment.kt
> +@AndroidEntryPoint
отступы

2023-10-26 16:27 UTC, ilsave commented
добавь пустую строчку в каждом файле, чтобы не было красного значка в конце

2023-10-30 11:54 UTC, merged